# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(max_length=110)),
                ('tipo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ideias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=110)),
                ('tipo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('tipo_nome', models.CharField(max_length=110)),
                ('estado', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('estado_nome', models.CharField(max_length=20)),
                ('problema', models.TextField(max_length=1700)),
                ('solucao', models.TextField(max_length=1700)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_pre_analise', models.DateTimeField(auto_now=True)),
                ('pre_analise', models.TextField(max_length=1700)),
                ('data_analise', models.DateTimeField(auto_now=True)),
                ('analise', models.TextField(max_length=1700)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('autor_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador2', to=settings.AUTH_USER_MODEL)),
                ('autor_pre_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador1', to=settings.AUTH_USER_MODEL)),
                ('tabela_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgidi.Analise')),
            ],
        ),
    ]
