# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgidi', '0002_auto_20170308_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analises',
            name='ordem',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
    ]
