# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgidi', '0004_auto_20170520_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conhecimentos',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='conhecimentos',
            name='object_id',
        ),
    ]
