# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgidi', '0007_auto_20170522_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asana', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=1700)),
                ('assignee', models.CharField(max_length=100, null=True)),
                ('assignee_status', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(null=True)),
                ('due_on', models.DateField(null=True)),
                ('due_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('current_status_text', models.TextField(max_length=1700)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgidi.Tasks')),
            ],
        ),
    ]
