# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgidi', '0008_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='current_status_text',
        ),
    ]
