# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgidi', '0009_remove_tasks_current_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sgidi.Tasks'),
        ),
    ]
