# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgidi', '0010_auto_20170525_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='section',
            field=models.BooleanField(default=False),
        ),
    ]
