# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgidi', '0011_tasks_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='projeto_id',
            field=models.CharField(default=210156681957457, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='section_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
